
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView codeField;
	private global::Gtk.FileChooserButton filechooserbutton1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TreeView lexemesTree;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.TreeView symbolTableTree;
	private global::Gtk.Label code;
	private global::Gtk.Label lexemes;
	private global::Gtk.Label symbolTable;
	private global::Gtk.Fixed fixed3;
	private global::Gtk.ScrolledWindow GtkScrolledWindow3;
	private global::Gtk.TextView console;
	private global::Gtk.Label label4;
	private global::Gtk.Button button3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.WidthRequest = 250;
		this.GtkScrolledWindow.HeightRequest = 250;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.codeField = new global::Gtk.TextView ();
		this.codeField.CanFocus = true;
		this.codeField.Name = "codeField";
		this.GtkScrolledWindow.Add (this.codeField);
		this.fixed1.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
		w2.X = 31;
		w2.Y = 51;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.filechooserbutton1 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserbutton1.WidthRequest = 120;
		this.filechooserbutton1.Name = "filechooserbutton1";
		this.fixed1.Add (this.filechooserbutton1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.filechooserbutton1]));
		w3.X = 125;
		w3.Y = 17;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.WidthRequest = 250;
		this.GtkScrolledWindow1.HeightRequest = 250;
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.lexemesTree = new global::Gtk.TreeView ();
		this.lexemesTree.CanFocus = true;
		this.lexemesTree.Name = "lexemesTree";
		this.GtkScrolledWindow1.Add (this.lexemesTree);
		this.fixed1.Add (this.GtkScrolledWindow1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow1]));
		w5.X = 328;
		w5.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.WidthRequest = 250;
		this.GtkScrolledWindow2.HeightRequest = 250;
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.symbolTableTree = new global::Gtk.TreeView ();
		this.symbolTableTree.CanFocus = true;
		this.symbolTableTree.Name = "symbolTableTree";
		this.GtkScrolledWindow2.Add (this.symbolTableTree);
		this.fixed1.Add (this.GtkScrolledWindow2);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow2]));
		w7.X = 616;
		w7.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.code = new global::Gtk.Label ();
		this.code.Name = "code";
		this.code.LabelProp = global::Mono.Unix.Catalog.GetString ("Code");
		this.fixed1.Add (this.code);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.code]));
		w8.X = 60;
		w8.Y = 25;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lexemes = new global::Gtk.Label ();
		this.lexemes.Name = "lexemes";
		this.lexemes.LabelProp = global::Mono.Unix.Catalog.GetString ("Lexemes");
		this.fixed1.Add (this.lexemes);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lexemes]));
		w9.X = 410;
		w9.Y = 26;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.symbolTable = new global::Gtk.Label ();
		this.symbolTable.Name = "symbolTable";
		this.symbolTable.LabelProp = global::Mono.Unix.Catalog.GetString ("Symbol Table");
		this.fixed1.Add (this.symbolTable);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.symbolTable]));
		w10.X = 692;
		w10.Y = 23;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.fixed1.Add (this.fixed3);
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.WidthRequest = 800;
		this.GtkScrolledWindow3.HeightRequest = 200;
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.console = new global::Gtk.TextView ();
		this.console.CanFocus = true;
		this.console.Name = "console";
		this.GtkScrolledWindow3.Add (this.console);
		this.fixed1.Add (this.GtkScrolledWindow3);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow3]));
		w13.X = 57;
		w13.Y = 428;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Console");
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w14.X = 61;
		w14.Y = 396;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button ();
		this.button3.WidthRequest = 800;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("EXECUTE");
		this.fixed1.Add (this.button3);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button3]));
		w15.X = 52;
		w15.Y = 348;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 906;
		this.DefaultHeight = 656;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
